### ISSUE TITLE
First horizontal line too short

### ISSUE THREAD

**Issue by filemon11** [bozsahin/ccg-latex#3]
The first horizontal line does not display properly:

![grafik](https://github.com/bozsahin/ccg-latex/assets/46485025/0dfbce70-8d44-424a-b4d2-326421190f73)

The following minimal example produces the error:

`\documentclass[nenglish, a4paper]{article}

\usepackage{ccg-latex}

\begin{document}

\begin{ccg}{4}{that & is & a & lie}{
\cgf{NP} & \cgf{(S\bs NP)\fs NP} & \cgf{NP\fs N} & \cgf{N} \\
 & & \cgline{2}{\cgfa} \\
 & & \cgres{2}{\cat{NP}} \\
 & \cgline{3}{\cgfa} \\
 & \cgres{3}{\cgf{S\bs NP}} \\
 \cgline{4}{\cgba} \\
 \cgres{4}{\cat{S}}
} 
\end{ccg}

\end{document}`

**Comment by bozsahin** [comment]
Yes I see it in my examples.pdf data as well. ccg and ccgg environments appear to always cause this problem but not the \cgex command, therefore \cglines command must be causing it. I will look into it soon. Thank you.

**Comment by bozsahin** [comment]
I pushed a new version to fix that. Seems to be working at my end. Does it work for you?

**Comment by filemon11** [comment]
It got better! I feel like it is still a bit short on the left side in some cases. For instance:

![grafik](https://github.com/bozsahin/ccg-latex/assets/46485025/8c0653f1-855b-4976-8c12-0dfd3f137572)

`\cgex{3}{I & do & that \\
\cglines{3}\\
\cgf{NP} & \cgf{(S\bs NP)\fs NP} & \cgf{NP} \\
& \cgline{2}{\cgfa} \\
& \cgres{2}{\cat{S\bs NP}} \\
\cgline{3}{\cgba} \\
\cgres{3}{\cat{S}}
}`

But definitely usable. Thanks a lot!

**Comment by bozsahin** [comment]
I made one more attempt. Seems to be slightly better for short material; NB. example in page 2. Thanks for your comments and feedback.
