### ISSUE TITLE
Use without lexical assumptions

### ISSUE THREAD

**Issue by filemon11** [bozsahin/ccg-latex#4]
Hello,
is it somehow possible to create derivations without lexical assumptions? E.g. for defining combinators. For instance:

![grafik](https://github.com/bozsahin/ccg-latex/assets/46485025/edd1c4fd-da08-4e1d-b779-43d409093308)

**Comment by bozsahin** [comment]
This is possible. I added an example to example.pdf for that, at the bottom of page 3. Thank you.
I am still trying to figure out the other issue you pointed out.

**Comment by filemon11** [comment]
Thank you!
